### ISSUE TITLE
Colour Picker doesn't work while running NVDA

### ISSUE THREAD

**Issue by afwaisbard** [ThePacielloGroup/CCA-Win#32] opened 2017-02-10 22:01 UTC
Can't use the Colour Picker while NVDA is running. It results with CCA getting stuck ("Not Responding"). 

OS: Windows 7.

**Comment by patrickhlauke** [comment] 2017-02-23 12:03
Can't reproduce in Windows 10, so may be a Windows 7 specific issue.

Could you try uninstalling CCA, installing the latest version https://github.com/ThePacielloGroup/CCA-Win/releases/tag/2.4.0.23 (and also updating NVDA with the most recent version, if you've not already) and seeing if the problem still persists?

**Comment by afwaisbard** [comment] 2017-02-25 08:11
I've tried it on Windows 8.1 as well, and could not reproduce it there either.

I was able to reproduce it on Windows 7 again using the latest CCA and latest NVDA.

The moment I click on the colour picker I see the process memory usage starting to climb at about 10k-12k per second. 

I just want to add something about this issue:
Once I realized that the reason is that I'm running NVDA with CCA, it's not that critical for me. I can always turn NVDA off for a moment while testing contrast with CCA. 
However, while not knowing this is the reason, it can be very frustrating. I even saw a guy at an accessibility conference trying to demo CCA colour picker, and he didn't understand why it got stuck (wish I could help him back then).
Meanwhile I'll do my best sharing this information with my colleagues so they'll be aware there's a workaround and not quit this tool for this.

**Comment by patrickhlauke** [comment] 2017-10-18 12:44
@afwaisbard I know this is now quite a while ago, but: any chance you could let me know if this is still an issue using the latest released version https://github.com/ThePacielloGroup/CCA-Win/releases/tag/2.5.0 ?

**Comment by burningmetals** [comment] 2018-04-27 11:18
I just installed the latest version of CCA-Win (2.5.0.0) on Windows 7 Enterprise 64 bit with service pack 1 and running NVDA 2018.1.1. I do not see any issue or conflict in running this combination.

Nice utility!

**Comment by patrickhlauke** [comment] 2018-04-27 12:49
thanks @burningmetals ... will close this then unless i hear otherwise

**Closed as completed by patrickhlauke** 2018-04-27 12:49 UTC
Labels: awaiting reply
